language: python

install:
  - pip install -r requirements.txt

script:
  # Use Sphinx to make the html docs
  - make singlehtml
  - touch _build/singlehtml/.nojekyll

# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  - provider: pages:git
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./build/singlehtml/
    keep_history: true